//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacion
    {
        public int Autorizacion_Id { get; set; }
        public Nullable<int> Autorizacion_IdAseguradora { get; set; }
        public Nullable<int> Autorizacion_IdProcedimiento { get; set; }
        public Nullable<System.DateTime> Autorizacion_FechaCreacion { get; set; }
        public Nullable<int> Autorizacion_IdUsuarioCreador { get; set; }
        public Nullable<bool> Autorizacion_Vigencia { get; set; }
        public Nullable<decimal> Autorizacion_Precio { get; set; }
        public Nullable<decimal> Autorizacion_Cobertura { get; set; }
        public Nullable<decimal> Autorizacion_Diferencia { get; set; }
        public Nullable<int> Autorizacion_NoAutorizacion { get; set; }
    
        public virtual Aseguradora Aseguradora { get; set; }
        public virtual ProcesoMedico ProcesoMedico { get; set; }
    }
}
