//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja_Usuario
    {
        public int Caja_Usuario_IdUsuario { get; set; }
        public int Caja_Usuario_IdCaja { get; set; }
        public Nullable<System.DateTime> Caja_Usuario_IdUsuario_FechaCreacion { get; set; }
        public Nullable<int> Caja_Usuario_IdUsuario_IdUsuarioCreador { get; set; }
        public Nullable<bool> Caja_Usuario_IdUsuario_Vigencia { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
