//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caja()
        {
            this.AperturaYCierreDeCaja = new HashSet<AperturaYCierreDeCaja>();
            this.Caja_Usuario = new HashSet<Caja_Usuario>();
        }
    
        public int Caja_Id { get; set; }
        public string Caja_Descripcion { get; set; }
        public Nullable<System.DateTime> Caja_FechaCreacion { get; set; }
        public Nullable<int> Caja_IdUsuarioCreador { get; set; }
        public Nullable<bool> Caja_Vigencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AperturaYCierreDeCaja> AperturaYCierreDeCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caja_Usuario> Caja_Usuario { get; set; }
    }
}
