//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_Factura
    {
        public int Cuenta_Factura_IdFactura { get; set; }
        public int Cuenta_Factura_IdCuenta { get; set; }
        public Nullable<decimal> Cuenta_Factura_Monto { get; set; }
        public System.DateTime Cuenta_Factura_FechaCreacion { get; set; }
        public Nullable<int> Cuenta_Factura_dUsuarioCreador { get; set; }
        public bool Cuenta_Factura_Vigencia { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual FacturaEncabezado FacturaEncabezado { get; set; }
    }
}
