//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaEncabezado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaEncabezado()
        {
            this.Cuenta_Factura = new HashSet<Cuenta_Factura>();
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
            this.ReciboIngreso = new HashSet<ReciboIngreso>();
        }
    
        public int FacturaEncabezado_Id { get; set; }
        public Nullable<int> FacturaEncabezado_IdNCF { get; set; }
        public string FacturaEncabezado_NCF { get; set; }
        public string FacturaEncabezado_IdCliente { get; set; }
        public string FacturaEncabezado_IdCajero { get; set; }
        public Nullable<decimal> FacturaEncabezado_TotalBruto { get; set; }
        public Nullable<decimal> FacturaEncabezado_TotalCobertura { get; set; }
        public Nullable<decimal> FacturaEncabezado_TotalItbis { get; set; }
        public Nullable<decimal> FacturaEncabezado_TotalDescuento { get; set; }
        public Nullable<decimal> FacturaEncabezado_TotalGeneral { get; set; }
        public Nullable<System.DateTime> FacturaEncabezado_FechaCreacion { get; set; }
        public Nullable<int> FacturaEncabezado_IdUsuarioCreador { get; set; }
        public Nullable<bool> FacturaEncabezado_Vigencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta_Factura> Cuenta_Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboIngreso> ReciboIngreso { get; set; }
    }
}
