//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public int FacturaDetalle_Id { get; set; }
        public Nullable<int> FacturaDetalle_IdFactura { get; set; }
        public Nullable<int> FacturaDetalle_PlanDeTratamiento { get; set; }
        public Nullable<decimal> FacturaDetalle_MontoBruto { get; set; }
        public Nullable<decimal> FacturaDetalle_MontoCobertura { get; set; }
        public Nullable<decimal> FacturaDetalle_MontoItbis { get; set; }
        public Nullable<decimal> FacturaDetalle_MontoDescuento { get; set; }
        public Nullable<decimal> FacturaDetalle_MontoTotal { get; set; }
        public Nullable<System.DateTime> FacturaDetalle_FechaCreacion { get; set; }
        public Nullable<int> FacturaDetalle_IdUsuarioCreador { get; set; }
        public Nullable<bool> FacturaDetalle_Vigencia { get; set; }
    
        public virtual FacturaEncabezado FacturaEncabezado { get; set; }
        public virtual PlanDeTratamiento PlanDeTratamiento { get; set; }
    }
}
