//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogGeneral
    {
        public int LogGeneral_Id { get; set; }
        public string LogGeneral_Pantalla { get; set; }
        public string LogGeneral_Accion { get; set; }
        public string LogGeneral_Mensaje { get; set; }
        public Nullable<System.DateTime> LogGeneral_Fecha { get; set; }
        public Nullable<int> LogGeneral_IdUsuario { get; set; }
        public Nullable<bool> LogGeneral_Vigencia { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
