//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCF
    {
        public int Id { get; set; }
        public Nullable<int> IdTipoNCF { get; set; }
        public Nullable<int> UltimaSecuenciaNIF { get; set; }
        public string Prefijo { get; set; }
        public Nullable<int> SecuenciaActual { get; set; }
        public Nullable<int> Limite { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdSucursal { get; set; }
    }
}
