//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int Pago_Id { get; set; }
        public string Pago_IdPersona { get; set; }
        public Nullable<int> Pago_IdCuenta { get; set; }
        public string Pago_Referencia { get; set; }
        public Nullable<double> Pago_Monto { get; set; }
        public Nullable<int> Pago_TipoPago { get; set; }
        public Nullable<System.DateTime> Pago_FechaCreacion { get; set; }
        public Nullable<int> Pago_IdUsuarioCreador { get; set; }
        public Nullable<bool> Pago_Vigencia { get; set; }
        public Nullable<int> Pago_IdCaja { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
