//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosPorPersona_View
    {
        public int Pago_Id { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> Cuenta { get; set; }
        public string Referencia { get; set; }
        public Nullable<double> Monto { get; set; }
        public string FormaPago { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Usuario { get; set; }
        public string Caja { get; set; }
    }
}
