//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Cuentas = new HashSet<Cuentas>();
            this.FacturaEncabezado = new HashSet<FacturaEncabezado>();
            this.FacturaEncabezado1 = new HashSet<FacturaEncabezado>();
            this.Pago = new HashSet<Pago>();
            this.PlanDeTratamiento = new HashSet<PlanDeTratamiento>();
            this.PlanDeTratamiento1 = new HashSet<PlanDeTratamiento>();
            this.ReciboIngreso = new HashSet<ReciboIngreso>();
            this.ReciboIngreso1 = new HashSet<ReciboIngreso>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public Nullable<int> Persona_TipoDocumento { get; set; }
        public string Persona_Documento { get; set; }
        public string Persona_Nombre { get; set; }
        public string Persona_Apellido { get; set; }
        public Nullable<int> Persona_TipoPersona { get; set; }
        public string Persona_CorreoElectronico { get; set; }
        public string Persona_Telefono { get; set; }
        public string Persona_Direccion { get; set; }
        public Nullable<int> Persona_IdAseguradora { get; set; }
        public Nullable<System.DateTime> Persona_FechaCreacion { get; set; }
        public Nullable<int> Persona_IdUsuarioCreador { get; set; }
        public Nullable<bool> Persona_Vigencia { get; set; }
    
        public virtual Aseguradora Aseguradora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuentas> Cuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaEncabezado> FacturaEncabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaEncabezado> FacturaEncabezado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual TipoPersona TipoPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanDeTratamiento> PlanDeTratamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanDeTratamiento> PlanDeTratamiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboIngreso> ReciboIngreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboIngreso> ReciboIngreso1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
