//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDeTratamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanDeTratamiento()
        {
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
        }
    
        public int PlanDeTratamiento_Id { get; set; }
        public Nullable<int> PlanDeTratamiento_IdProcedimiento { get; set; }
        public Nullable<int> PlanDeTratamiento_NoAutorizacion { get; set; }
        public string PlanDeTratamiento_IdPaciente { get; set; }
        public string PlanDeTratamiento_IdMedico { get; set; }
        public string PlanDeTratamiento_Causa { get; set; }
        public string PlanDeTratamiento_Resultado { get; set; }
        public byte[] PlanDeTratamiento_Imagen { get; set; }
        public Nullable<System.DateTime> PlanDeTratamiento_FechaCreacion { get; set; }
        public Nullable<int> PlanDeTratamiento_IdUsuarioCreador { get; set; }
        public Nullable<bool> PlanDeTratamiento_Vigencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
        public virtual ProcesoMedico ProcesoMedico { get; set; }
    }
}
