//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesoMedico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcesoMedico()
        {
            this.Autorizacion = new HashSet<Autorizacion>();
            this.PlanDeTratamiento = new HashSet<PlanDeTratamiento>();
        }
    
        public int ProcesoMedico_Id { get; set; }
        public string ProcesoMedico_Descripcion { get; set; }
        public Nullable<decimal> ProcesoMedico_Precio { get; set; }
        public Nullable<System.DateTime> ProcesoMedico_FechaCreacion { get; set; }
        public Nullable<int> ProcesoMedico_IdUsuarioCreador { get; set; }
        public Nullable<bool> ProcesoMedico_Vigencia { get; set; }
        public Nullable<int> ProcesoMedico_IdTipoProceso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorizacion> Autorizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanDeTratamiento> PlanDeTratamiento { get; set; }
        public virtual TipoProceso TipoProceso { get; set; }
    }
}
