//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboIngreso
    {
        public int ReciboIngreso_Id { get; set; }
        public string ReciboIngreso_IdPaciente { get; set; }
        public string ReciboIngreso_IdCajero { get; set; }
        public Nullable<decimal> ReciboIngreso_Monto { get; set; }
        public Nullable<int> ReciboIngreso_IdCuentaDetalle { get; set; }
        public Nullable<System.DateTime> ReciboIngreso_FechaCreacion { get; set; }
        public Nullable<int> ReciboIngreso_IdUsuarioCreador { get; set; }
        public Nullable<bool> ReciboIngreso_Vigencia { get; set; }
    
        public virtual FacturaEncabezado FacturaEncabezado { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
    }
}
