//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoNCF
    {
        public int TipoNCF_Id { get; set; }
        public string TipoNCF_Descripcion { get; set; }
        public Nullable<int> TipoNCF_IdUsuario { get; set; }
        public Nullable<System.DateTime> TipoNCF_FechaCreado { get; set; }
        public bool TipoNCF_Estado { get; set; }
        public Nullable<int> TipoNCF_IdSucursal { get; set; }
    }
}
