//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoProceso()
        {
            this.ProcesoMedico = new HashSet<ProcesoMedico>();
        }
    
        public int TipoProceso_Id { get; set; }
        public string TipoProceso_Descripcion { get; set; }
        public Nullable<System.DateTime> TipoProceso_FechaCreacion { get; set; }
        public Nullable<int> TipoProceso_IdUsuarioCreador { get; set; }
        public Nullable<bool> TipoProceso_Vigencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesoMedico> ProcesoMedico { get; set; }
    }
}
