//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.AperturaYCierreDeCaja = new HashSet<AperturaYCierreDeCaja>();
            this.Caja_Usuario = new HashSet<Caja_Usuario>();
            this.Egreso = new HashSet<Egreso>();
            this.LogGeneral = new HashSet<LogGeneral>();
            this.Pago = new HashSet<Pago>();
        }
    
        public int Usuario_Id { get; set; }
        public string Usuario_Nickname { get; set; }
        public string Usuario_Contraseña { get; set; }
        public int Usuario_IdPerfil { get; set; }
        public string IdPersona { get; set; }
        public System.DateTime Usuario_FechaCreacion { get; set; }
        public Nullable<int> Usuario_IdUsuarioCreador { get; set; }
        public bool Usuario_Vigencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AperturaYCierreDeCaja> AperturaYCierreDeCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caja_Usuario> Caja_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egreso> Egreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogGeneral> LogGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
